const actionTypes = {
PROFILE_UPDATE_SUCCESS:"PROFILE_UPDATE_SUCCESS",
PROFILE_UPDATE_FAILURE:"PROFILE_UPDATE_FAILURE",
GET_PROFILE_SUCCESS:"GET_PROFILE_SUCCESS",
GET_PROFILE_FAILURE:"GET_PROFILE_FAILURE",
CHANGE_PASSWORD_SUCCESS:"CHANGE_PASSWORD_SUCCESS",
CHANGE_PASSWORD_FAILURE:"CHANGE_PASSWORD_FAILURE"
}
export default actionTypes;